### ISSUE TITLE
Change size and position of remove avatar icon

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1493]
Proposed:
![meathead](https://cloud.githubusercontent.com/assets/68213/3780870/46803588-1990-11e4-973f-53d4e5985d09.png)

My CSS, though not sure how this will behave in responsive mode.

``` css
.main-avatar .remove {
    position: absolute;
    right: 50px;
    text-decoration: none;
    top: -4px;
    font-size: 24px;
}
```
