### ISSUE TITLE
Refactor the Sass into smaller modules

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1661]
Currently our [_general.scss](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/_general.scss) file is a lovely 913 line masterpiece. It may be nice to break that into smaller, more manageable, files.  For example, break out any marketing snippet specific styles into a separate include file. Or tooltips.

Plus, here's a couple handy little mixins we could potentially use:
```scss
@mixin input-placeholder {
  &:-moz-placeholder, /* Firefox 18- */
  &::-moz-placeholder,  /* Firefox 19+ */
  &::webkit-input-placeholder,
  &:-ms-input-placeholder {
    @content;
  }
}

@mixin appearance($value:none) {
  // autoprefixer does not handle appearance, see https://github.com/ai/autoprefixer/issues/205
  -moz-appearance: $value;
  -webkit-appearance: $value;
  appearance: $value;
  // Some hackery for Firefox since moz-appearance: none doesn't remove the arrow
  text-indent: 0.01px;
}

input {
  @include input-placeholder {
    color: red;
  };
}

select {
  @include appearance(none);
}
```
