### ISSUE TITLE
Add some Sass linting

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#3372]
Currently we have unofficial [**scss-lint**](https://github.com/brigade/scss-lint) support (see [/app/styles/.scss-lint.yml](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/.scss-lint.yml) for current rules), although you have to run it manually (`$ scss-lint app/styles/**/*.scss`) and requires a Ruby gem.

It'd be nice if we could convert it to something pure-Node and possibly add it to our linting pipeline. I've used [**sass-lint**](https://github.com/sasstools/sass-lint) on other projects with some success.

Currently, running `$ scss-lint` against master gives us around 177 warnings/errors, so we probably need to clean up some Sass and tweak some rules.

**Comment by pdehaan** [comment]
Here's a _really_ rough .sass-lint.yml file:
```yml
rules:
  clean-import-paths: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero: 0
  mixins-before-declarations: 0
  nesting-depth: [2, max-depth: 4]
  no-css-comments: 0
  no-empty-args: 0
  no-ids: 0
  no-important: 0
  no-mergeable-selectors: 0
  no-qualifying-elements: 0
  no-vendor-prefixes: 0
  no-warn: 0
  shorthand-values: 0
  space-around-operator: 0
```

If you have **sass-lint** installed globally, you can run it using this command (turns out the `-v` flag is pretty important, otherwise you won't see any warnings):
```sh
$ sass-lint app/styles/**/*.scss -v
```

Or, if we add [**grunt-sass-lint**](https://github.com/sasstools/grunt-sass-lint), something like this:
```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

module.exports = function (grunt) {
  grunt.config('sasslint', {
    sass: ['<%= yeoman.app %>/styles/**/*.scss']
  });
};
```
