### ISSUE TITLE
Odd value for -webkit-transition-duration in main.css

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#438]
### Steps to reproduce:
1. [app/styles/main.css#L399](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/main.css#L399)
2. [app/styles/main.css#L411](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/main.css#L411)
### Actual results:

``` css
-webkit-transition-duration:150px;
```
### Expected results:

Change the `transition-duration` from 150px to 150ms.

``` css
.privacy-links:hover a {
  color: #0096DD;
  transition-duration: 150ms;
  -moz-transition-duration: 150ms;
  -webkit-transition-duration: 150ms;
}
```

PR incoming shortly.
