### ISSUE TITLE
TODO: Consider the .hidden style (?!)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#558]
via #555 

[app/styles/main.css#L685](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/main.css#L685)

``` css
/* TODO: These need further consideration */

.hidden {
  display: none;
}
```
