### ISSUE TITLE
Confusing repeated rules in CSS

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#575]
See [app/styles/main.css#L590-L592](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/main.css#L590-L592)

``` css
/**
 * Hover over the show password label in its dark state
 */
input[type="text"] ~ .show-password:focus + .show-password-label,
input[type="text"] ~ .show-password:focus + .show-password-label,
input[type="text"] ~ .show-password:focus + .show-password-label,
input[type="text"] ~ .show-password-label:focus,
input[type="text"] ~ .show-password-label:active,
input[type="text"] ~ .show-password-label:hover {
  /*background: #f2f2f2;*/
  background: #9AABB8;
  color: #fff;
}
```

Those first three lines (`input[type="text"] ~ .show-password:focus + .show-password-label`) look _preeeetty_ similar to me. Did we mean to swap the :focus with :active and :hover, or can we delete a couple lines of code?

/summon @shane-tomlinson
