### ISSUE TITLE
Duplicated style in main.scss

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#599]
### Steps to repro:
1. [app/styles/main.scss#L585-L587](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/main.scss#L585-L587)
### Actual results:

`.show-password:focus + .show-password-label` is defined twice:

``` css
.show-password-label:hover,
.show-password-label:active,
.show-password-label:focus,
.show-password:focus + .show-password-label,
.show-password:active + .show-password-label,
.show-password:focus + .show-password-label {
  background: $html-background-color;
  color: $text-color;
  outline: none;
}
```
### Expected results:

Me thinks one of them should be `.show-password:hover + .show-password-label`.
