### ISSUE TITLE
Grunt CSSLint task tells us the fonts are using bulletproof syntax

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#964]
Found in 70c88e76cc26f7dd9f4e0b9426908260fd3a8ab6

### Steps to reproduce:
1. Run `$ grunt csslint`

### Actual results:

```bash
$ grunt csslint
```

> Running "csslint:strict" (csslint) task
> Linting app/styles/fonts.css ...ERROR

> - [L6:C3] @font-face declaration doesn't follow the fontspring bulletproof syntax. Use the bulletproof @font-face syntax to avoid 404's in old IE (http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax). (bulletproof-font-face)

> - [L13:C3] @font-face declaration doesn't follow the fontspring bulletproof syntax. Use the bulletproof @font-face syntax to avoid 404's in old IE (http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax). (bulletproof-font-face)

> - [L20:C3] @font-face declaration doesn't follow the fontspring bulletproof syntax. Use the bulletproof @font-face syntax to avoid 404's in old IE (http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax). (bulletproof-font-face)

> Warning: Task "csslint:strict" failed. Use --force to continue.

> Aborted due to warnings.

And the generated app/styles/fonts.css file is as follows:

```css
@font-face {
  font-family: 'Fira Sans';
  font-style: normal;
  font-weight: 400;
  src: url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-regular.eot');
  src: local('Fira Sans'),
    local('FiraSans'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-regular.eot#') format('embedded-opentype'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-regular.woff') format('woff'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-regular.ttf') format('truetype'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-regular.svg#Fira Sans') format('svg'); }

@font-face {
  font-family: 'Fira Sans';
  font-style: normal;
  font-weight: 300;
  src: url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-light.eot');
  src: local('Fira Sans Light'),
    local('FiraSansLight'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-light.eot#') format('embedded-opentype'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-light.woff') format('woff'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-light.ttf') format('truetype'),
    url('/bower_components/connect-fonts-firasans/fonts/latin/firasans-light.svg#Fira Sans') format('svg'); }

@font-face {
  font-family: 'Clear Sans';
  font-style: normal;
  font-weight: 400;
  src: url('/bower_components/connect-fonts-clearsans/fonts/latin/clearsans-regular.eot');
  src: local('Clear Sans'),
    local('ClearSans'),
    url('/bower_components/connect-fonts-clearsans/fonts/latin/clearsans-regular.eot#') format('embedded-opentype'),
    url('/bower_components/connect-fonts-clearsans/fonts/latin/clearsans-regular.woff') format('woff'),
    url('/bower_components/connect-fonts-clearsans/fonts/latin/clearsans-regular.ttf') format('truetype'),
    url('/bower_components/connect-fonts-clearsans/fonts/latin/clearsans-regular.svg#Clear Sans') format('svg'); }
```
